FROM golang:1.8.3 as builder
RUN mkdir -p /go/src/github.com/gianksp/mailer
WORKDIR /go/src/github.com/gianksp/mailer

COPY . .

RUN cd server \
    && go get ./... \
    && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM scratch as mailer-server
COPY --from=0 /go/src/github.com/gianksp/mailer/server/main .
CMD ["/main"]
